USSC.Web/Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace USSC.Web.Controllers
{
    public class ApplicationsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

USSC.Web/Views/Shared/Denied.cshtml
<h1>Доступ запрещен</h1>

<p>У вас недостаточно прав для доступа к этому разделу.</p>

USSC.Web/Views/Shared/_Layout.cshtml
@inject IUserDataService dataService
@inject IAccessManager accessManager

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Воронежские алмазы</title>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/main.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <header class="header">
        <div class="header__logo">
            ООО &laquo;Воронежские алмазы&raquo;
        </div>
        @if (User.Identity.IsAuthenticated)
        {
            var userData = await dataService.GetUserData(User.Identity.Name);
            
            <div class="header__profile">
                <div class="header__name">
                    @userData.LastName 
                    @userData.Name 
                    @userData.Patronymic, 
                    
                    @if (userData.Organization != null)
                    {
                        @userData.Organization.Name;
                    }
                    else
                    {
                        var roles = string.Join(", ", await dataService.GetUserRoles(userData.Id));
                        @roles
                    }

                </div>
                <a class="header__btn" asp-controller="Account" asp-action="Logout">Выход</a>
            </div>
        }
        else
        {
            <div class="header__profile">
                <a class="header__btn" asp-controller="Account" asp-action="Login">Вход</a>
            </div>
        }

    </header>

    @if (User.Identity.IsAuthenticated){
        var data = await dataService.GetUserData(User.Identity.Name);
        var isAdmin = await accessManager.IsAdmin(data.Id);

        if (isAdmin)
        {
        <div class="page-wrapper">
            <div class="page page_nav">
                <nav class="nav">
                    <div class="nav__item">
                        <a asp-controller="Admin" asp-action="Index">Администрирование</a>
                    </div>
                    <div class="nav__item">
                        <a asp-controller="Organization" asp-action="Index">Подрядные организации</a>
                    </div>
                    <div class="nav__item">
                        <a asp-controller="Applications" asp-action="Index">Заявки</a>
                    </div>
                </nav>
            </div>
        </div>
        }
    }

    <div class="page-wrapper">
        <div class="page page_main">
            @RenderBody()
        </div>
    </div>

    <script src="~/js/script.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>